# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches-ignore:
      - 'dev'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Install add-on
      run: dotnet tool install --global dotnet-zip && dotnet tool install --global dotnet-tarball && dotnet tool install --global dotnet-rpm && dotnet tool install --global dotnet-deb
    - name: Build
      run: bash ./build.sh
    - name: Upload a Release
      uses: actions/upload-artifact@v4.3.1
      with:
          name: Release
          path: /home/runner/work/webone-kozaic/webone-kozaic/bin/Release/net6.0/
    - name: Upload a ReleaseSC
      uses: actions/upload-artifact@v4.3.1
      with:
          name: ReleaseSC
          path: /home/runner/work/webone-kozaic/webone-kozaic/bin/ReleaseSC/net6.0/
